version: '3.4'

services:
  crumb:
    restart: unless-stopped
    image: crumb
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      DOMAIN: https://crumb.sccs.swarthmore.edu/
      MONGODB_URI: mongodb://db:27017
      MONGODB_DB: crumb
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      - 'traefik.http.routers.crumb.entrypoints=https'
      - 'traefik.http.routers.crumb.rule=Host(`crumb.sccs.swarthmore.edu`)'
      - 'traefik.http.routers.crumb.tls=true'
      - 'traefik.http.routers.crumb.tls.certresolver=letsEncrypt'
      - 'traefik.http.services.crumb.loadbalancer.server.port=3434'
    container_name: crumb-docker
    command: npm run start
    networks:
      - internal
      - traefik

  db:
    image: mongo:latest
    # first-time database initialization
    environment:
      MONGO_INITDB_DATABASE: crumb
    volumes:
      - ./dev/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - internal

networks:
  internal:
  traefik:
    external: true
    driver: bridge
