version: '3.4'

services:
  crumb:
    init: true
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development
      DOMAIN: http://127.0.0.1:3000/
      MONGODB_URI: mongodb://db:27017
      MONGODB_DB: crumb
    ports:
      - 3000:3000
      - 9229:9229
      - 5555:5555
    command: sh -c "npm install --silent && npm run dev "

  db:
    image: mongo:latest
