version: '3.4'

services:
  crumb:
    restart: unless-stopped
    image: crumb
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      DOMAIN: http://127.0.0.1:3434/
      MONGODB_URI: mongodb://db:27018
      MONGODB_DB: crumb
    ports:
      - 3434:3434
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      - 'traefik.http.routers.crumb.entrypoints=https'
      - 'traefik.http.routers.crumb.rule=Host(`crumb.sccs.swarthmore.edu`)'
      - 'traefik.http.routers.crumb.tls=true'
      - 'traefik.http.routers.crumb.tls.certresolver=letsEncrypt'
      - 'traefik.http.services.crumb.loadbalancer.server.port=3434'
    container_name: crumb-docker
    command: npm run start
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - traefik

  db:
    image: mongo:latest
    # first-time database initialization
    environment:
      MONGO_INITDB_DATABASE: crumb
    volumes:
      - ./dev/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - 127.0.0.1:27018:27018

networks:
  traefik:
    external: true
    driver: bridge
